name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-rltgoDzvO --delete"
          local-path: "./"
          server: ${{ secrets.SERVER }}
          remote-path: "/path/to/your/repo"
